# Generated by Django 4.2.27 on 2026-02-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
